### ISSUE TITLE
CI build-binary requires release

### ISSUE THREAD

**Issue by nicolaiunrein** [nicolaiunrein/cargo-get#10]
@meysam81 the implementation of the build-binary.yml is not ideal as it uses the latest release instead of the newly built binary.

**Comment by meysam81** [comment]
Yes, having the `CI` in place means that you get an assurance of passing builds in your pull-requests as well as the default branch `master`.
That said, the build-binary as well as the github-actions should pin to a specific tag, ideally `v1` as is common around the GitHub community.

**Comment by nicolaiunrein** [comment]
I think I would actually prefer a setup like this as I do in other projects. 

- run CI.yml on push and PR
- run build-binary on tag push and make it create a release
- run github-action.yml on new releases to create the action

This automatically releases a new version whenever I push a new tag. build-binary/github-action.yml should also have a manual trigger. In the current setup I need to manually create a new gh release which I will eventually forget 😂

**Comment by meysam81** [comment]
So, I think the naming isn't good, and that's on me. Because the `github-actions` was meant to be more of a `self-test-action` so that the repository would dig out the bugs before the users do.

`CI` and the triggers are good, however, and nothing against that.

The build-binary also has a good trigger IMO, considering that it won't push any asset unless it's a release.

Based on what you want, I'm thinking there might be a need for another workflow that is doing this exact thing: "Do a GitHub release when a new tag is pushed"
